language: python
python:
  - "2.7"
install: 
  - pip install -r test_requirements.txt
  - pip install coveralls
  - python setup.py install
script:
  - cd forex/tests
  - ./runtests.py
  - mv .coverage ../../
  - cd ../../
after_success: 
  - coveralls
