language: python

python:
  - 2.7

env:
  - DJANGO=Django==1.8.1

install:
  - pip install $DJANGO
  - pip install coverage coveralls
  - pip install numpy>=1.6.1
  - pip install pandas>=0.12.0

script:
  - coverage run -a setup.py test
  - coverage report
after_success: coveralls
