language: python
python:
  - "2.7"
install: 
  - pip install -r test_requirements.txt
  - pip install coveralls
  - python setup.py install
script:
  - python setup.py test
after_success: 
  - coveralls
